name: yoloongppt

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    working_dir: /workspace
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
