"""DEC-039/040 independent executable revision and completion decisions."""
import copy
import time
from .artifacts import entity
from .errors import TaskError,trace_id
from .revision_plans import build_plan
from .narrative import MAPPING

DEFAULT_COVERAGE=('structure','editability','geometry','fact_numeric','visual_semantic','fact_semantic','accessibility','global_consistency','powerpoint_compatibility')

def _error(code,message):raise TaskError(code,message,'QualityDecisions',['DEC-039','DEC-040','QA-019','QA-020'])

def _all_issues(report):
 issues=list(report.get('issues',[]));issues.extend(report.get('model_review',{}).get('issues',[]))
 return issues

def completion(report,plan,policy=None,prior_traces=None):
 policy=policy or {};prior_traces=prior_traces or []
 if set(policy)-{'required_coverage','allow_partial_warning','retry_count','max_retries','required_nodes','acceptance_required'}:_error('COMPLETION_POLICY_UNSUPPORTED','终止策略字段未登记，未忽略。')
 issues=_all_issues(report)
 if any(i.get('severity') not in {'P0','P1','P2'} for i in issues):_error('QUALITY_SEVERITY_INVALID','质量问题严重度未登记。')
 p0=sum(i['severity']=='P0' for i in issues);reported=report.get('p0_issue_count')
 if reported is not None and reported!=p0:_error('QUALITY_P0_COUNT_MISMATCH','P0统计与实际问题不一致，不能决定终止。')
 retry=policy.get('retry_count',0);maximum=policy.get('max_retries',2)
 if any(not isinstance(n,int) or isinstance(n,bool) or n<0 for n in (retry,maximum)):_error('QUALITY_RETRY_POLICY_INVALID','重试次数必须是非负整数。')
 requested=policy.get('required_coverage',[])
 required=list(dict.fromkeys([*DEFAULT_COVERAGE,*requested])) if isinstance(requested,list) else requested
 if not isinstance(required,list) or any(not isinstance(n,str) for n in required) or len(set(required))!=len(required):_error('QUALITY_COVERAGE_POLICY_INVALID','required_coverage需唯一字符串数组。')
 coverage=report.get('coverage',{});missing=[n for n in required if coverage.get(n) not in {'complete','passed','verified'}]
 executed={t.get('node_id') for t in prior_traces if t.get('error') is None and t.get('output') is not None}
 requested_nodes=policy.get('required_nodes',[])
 if not isinstance(requested_nodes,list) or any(not isinstance(n,str) for n in requested_nodes):_error('QUALITY_NODE_POLICY_INVALID','required_nodes需字符串数组。')
 # The full baseline decision chain cannot be erased by an empty policy list.
 # DEC-039 is generated by this call; DEC-040 is this completion decision.
 required_nodes=list(dict.fromkeys([*[f'DEC-{i:03d}' for i in range(1,39)],*requested_nodes]))
 missing_nodes=[n for n in required_nodes if n not in executed]
 errors=[{'node_id':t.get('node_id'),'error':copy.deepcopy(t['error'])} for t in prior_traces if t.get('error')]
 acceptance=report.get('acceptance',{});requested_ac=policy.get('acceptance_required',[])
 if not isinstance(requested_ac,list) or any(not isinstance(n,str) for n in requested_ac):_error('QUALITY_ACCEPTANCE_POLICY_INVALID','acceptance_required需字符串数组。')
 required_ac=list(dict.fromkeys(['AC-001','GOV-008',*requested_ac]));missing_ac=[n for n in required_ac if acceptance.get(n)!='passed']
 reasons=[]
 if p0:state='fail';reasons.append('Unresolved P0 issues block final output')
 elif errors:state='fail';reasons.append('Earlier decision errors are retained and prevent final output')
 elif missing or missing_nodes or missing_ac or issues or plan['status']!='ready':
  state='warning' if policy.get('allow_partial_warning',True) else 'fail';reasons.append('Coverage/acceptance/revision conditions are incomplete or nonblocking issues remain')
 else:state='final';reasons.append('All explicitly required coverage, node and acceptance evidence is verified and no issues remain')
 retryable=state=='fail' and plan['status']=='ready' and bool(plan['actions']) and retry<maximum and not errors
 return {'state':state,'final_allowed':state=='final','p0_issue_count':p0,'warning_issue_count':len(issues)-p0,'missing_coverage':missing,'missing_nodes':missing_nodes,'missing_acceptance':missing_ac,'revision_plan_status':plan['status'],'reasons':reasons,'retry':{'count':retry,'maximum':maximum,'allowed':retryable,'next_action':'execute_revision_plan' if retryable else 'provide_required_input_or_fail' if p0 else 'complete_missing_acceptance'},'error':{'code':'QUALITY_P0_UNRESOLVED','issue_ids':[i.get('issue_id') for i in issues if i['severity']=='P0']} if p0 else {'code':'UPSTREAM_DECISION_FAILED','errors':errors} if errors else None,'system_acceptance':'passed' if state=='final' and all(acceptance.get(f'AC-{i:03d}')=='passed' for i in range(1,31)) else 'not_passed'}

def _trace(node,input_,candidates,selected,output,trace,start):
 converted=[{'node_id':node,'candidate_id':entity('candidate'),'value':v,'score':score,'reasons':[{'reason':reason}],'evidence_refs':[],'constraints':[{'no_p0_final':True,'preserve_facts':True,'preserve_locks':True}]} for v,score,reason in candidates]
 return {'trace_id':trace,'node_id':node,'input':copy.deepcopy(input_),'candidates':converted,'selected':[converted[selected]['candidate_id']],'rules':{'source_project_mapping':MAPPING,'score_semantics':'deterministic policy precedence; not confidence','confidence':'unknown','fallback':'explicit fail or requires_user_input; never silent repair','retry':copy.deepcopy(output.get('retry',{'allowed':False,'reason':'RevisionPlan consumption required'}))},'output':copy.deepcopy(output),'duration':max(0,time.monotonic()-start),'error':copy.deepcopy(output.get('error'))}

def decide(document,schemas=None,trace=None):
 trace=trace or trace_id();start=time.monotonic()
 if schemas:schemas.validate('quality-stage-input.schema.json',document)
 if set(document)-{'quality_report','deck','object_map','revision_policy','completion_policy','prior_traces','parent_run_id'}:_error('QUALITY_DECISION_INPUT_UNSUPPORTED','质量决策输入字段未登记。')
 report=copy.deepcopy(document['quality_report']);deck=document['deck'];objmap=document['object_map'];orders={s['order']:s['slide_id'] for s in deck['slides']}
 issues=_all_issues(report)
 # Model review's slide_order is resolved to the stable slide ID. No object guessed.
 for i in issues:
  if not i.get('slide_id') and i.get('slide_order') in orders:i['slide_id']=orders[i['slide_order']]
  if not i.get('issue_id'):i['issue_id']=entity('issue')
  i.setdefault('code','MODEL_'+str(i.get('type','SEMANTIC')).upper());i.setdefault('action',{'node':'semantic','mode':'requires_user_input','reason':'Independent review issue needs grounded decision'})
 plan=build_plan(deck,objmap,issues,document.get('revision_policy'),trace,document.get('parent_run_id'))
 d39=_trace('DEC-039',{'issues':issues,'revision_policy':document.get('revision_policy',{}),'deck':deck,'object_map':objmap},[(plan,1,'Local plan with preserved locks, all issues mapped'),({'status':'fail'},0,'Explicit fail if no safe repair/input available')],0,plan,trace,start)
 report['issues']=issues;report.pop('model_review',None)
 result=completion(report,plan,document.get('completion_policy'),document.get('prior_traces'))
 d40=_trace('DEC-040',{'quality_report':report,'revision_plan':plan,'completion_policy':document.get('completion_policy',{}),'prior_traces':document.get('prior_traces',[])},[({'state':s},1 if result['state']==s else 0,'No P0 final; incomplete coverage warning or explicit fail') for s in ('final','warning','fail')],('final','warning','fail').index(result['state']),result,trace,start)
 output={'revision_plan':plan,'completion':result,'decision_traces':[d39,d40]}
 if schemas:schemas.validate('revision-plan-runtime-output.schema.json',plan);schemas.validate('quality-stage-output.schema.json',output)
 return output

def run_node(document,node_id,schemas=None,trace=None):
 if node_id not in {'DEC-039','DEC-040'}:_error('QUALITY_NODE_UNSUPPORTED','当前质量节点仅DEC-039/040。')
 result=decide(document,schemas,trace)
 return {'node_id':node_id,'output':result['revision_plan'] if node_id=='DEC-039' else result['completion'],'decision_trace':next(t for t in result['decision_traces'] if t['node_id']==node_id)}
