"""Native asset dimensions metadata namespace positive/negative checks; no model/render."""
import copy,json,hashlib
from pathlib import Path
from pptx import Presentation
from yoloongppt.quality import check,verified_asset_notes,numbers
root=Path('/runtime/runs/dbb3a53c-1c15-4fdd-aa73-e66560ce7b77');load=lambda n:json.loads((root/n).read_text('utf-8'));deck=load('deck-spec.json');presentation=Presentation(root/'deck.pptx');spec=next(s for s in deck['slides'] if any(e['type']=='image' for e in s['elements']));native=presentation.slides[spec['order']];notes=spec['content']['notes'];image=next(e for e in spec['elements'] if e['type']=='image');asset_id=image['data']['asset_id'];checks=[]
def test(name,condition,observed):checks.append({'name':name,'passed':bool(condition),'observation':observed});assert condition,name
mask,verified=verified_asset_notes(notes,spec,native);test('actual_png_dimensions_metadata_verified',not {'320','160'}&numbers(mask) and len(verified)==1 and verified[0]['matched_span']=='320×160 PNG' and verified[0]['asset_id']==asset_id and verified[0]['sha256']==image['data']['sha256'],verified)
# Positive dimensions cannot grant permission to numerically equal business quantities.
business=notes+' 同时声称业务耗电320千瓦时。';mask,verified=verified_asset_notes(business,spec,native);test('same_value_business_quantity_not_allowed', '320' in numbers(mask) and len(verified)==1,{'numbers_after_metadata_mask':sorted(numbers(mask))})
wrong=notes.replace('320×160 PNG','999×160 PNG');mask,verified=verified_asset_notes(wrong,spec,native);noasset=notes.replace(asset_id,'asset_00000000-0000-0000-0000-000000000000');other_mask,other_verified=verified_asset_notes(noasset,spec,native);prefix_mask,prefix_verified=verified_asset_notes(notes.replace(asset_id,asset_id+'_fake'),spec,native);mismatch=copy.deepcopy(spec);next(e for e in mismatch['elements'] if e['type']=='image')['data']['sha256']='0'*64;hash_mask,hash_verified=verified_asset_notes(notes,mismatch,native);test('wrong_dimensions_fake_asset_hash_fail_closed',not verified and {'999','160'}<=numbers(mask) and not other_verified and {'320','160'}<=numbers(other_mask) and not hash_verified and {'320','160'}<=numbers(hash_mask) and not prefix_verified and {'320','160'}<=numbers(prefix_mask),{'wrong_dimensions_mask':mask,'fake_asset_verifications':other_verified,'hash_mismatch_verifications':hash_verified})
qa=check(deck,root/'deck.pptx',load('object-map.json'),load('approved-source-result.json'),load('render-report.json'),root);test('real_6page_direct_qa_preserves_notes_and_resolution_warning',not any(i['code']=='FACT_NOTE_NUMBER_UNSUPPORTED' and i['slide_id']==spec['slide_id'] for i in qa['issues']) and any(i['code']=='IMAGE_RESOLUTION_LOW' for i in qa['issues']) and deck['slides'][spec['order']]['content']['notes']==notes,{'p0_count':qa['p0_issue_count'],'issues':[i['code'] for i in qa['issues']]})
out=Path('/runtime/quality-asset-note-validation');out.mkdir(exist_ok=True);(out/'quality-after-metadata-check.json').write_text(json.dumps(qa,ensure_ascii=False,indent=2)+'\n','utf-8');p=Path('/workspace/src/yoloongppt/quality.py');report={'passed':all(c['passed'] for c in checks),'checks':checks,'run_id':root.name,'original_notes':notes,'verified_asset_metadata':[c for c in qa['checks'] if c['kind']=='asset_metadata_namespace'],'source_hashes':{str(p.relative_to('/workspace')):hashlib.sha256(p.read_bytes()).hexdigest()},'pptx_sha256':hashlib.sha256((root/'deck.pptx').read_bytes()).hexdigest(),'model_calls':0,'render_calls':0,'system_acceptance':'not_passed'};(out/'quality-asset-note-runtime.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n','utf-8');print(json.dumps({'passed':report['passed'],'checks':len(checks),'p0_count':qa['p0_issue_count']},ensure_ascii=False))
