"""Build source-backed candidate maps, with explicit unimplemented boundaries."""
import ast,hashlib,json,re
from pathlib import Path
root=Path('F:/YoloongPPT-Research/P05');out=Path('F:/YoloongPPT/research/P05')
baseline=json.loads(Path('F:/YoloongPPT-Temp-P01-05/p05-baseline-rows.json').read_text(encoding='utf-8'))
commit='5ae0670747885c464aa8063329a902d80a251877'
sources={}
def ref(path,symbol=None):
 text=(root/path).read_text(encoding='utf-8');sources[path]=hashlib.sha256((root/path).read_bytes()).hexdigest()
 if symbol and path.endswith('.py'):
  tree=ast.parse(text);matches=[n for n in ast.walk(tree) if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef)) and n.name==symbol]
  assert matches,(path,symbol)
  node=matches[0];a,b=node.lineno,node.end_lineno
 elif symbol:
  lines=text.splitlines();a=next(i+1 for i,l in enumerate(lines) if re.match(r'(?:async )?function '+re.escape(symbol)+r'\(',l));b=next((i for i,l in enumerate(lines[a:],a+1) if re.match(r'(?:async )?function ',l)),len(lines)+1)-1
 else:a,b=1,len(text.splitlines())
 return {'path':path,'symbol':symbol,'line_start':a,'line_end':b,'sha256':sources[path]}
def refs(path,*symbols):return [ref(path,s) for s in symbols]
smart='python_backend/smart_layer.py';js='generate-ppt.js';template='python_backend/template_engine.py';py='python_backend/pptx_renderer.py'
nodes=[]
def decision(id,decs,name,inp,candidates,mechanism,output,fallback,src,state='source_inspected',evidence=None):
 nodes.append(dict(id=id,dec_ids=[f'DEC-{n:03}' for n in decs],name=name,input=inp,candidates=candidates,mechanism=mechanism,output=output,fallback=fallback,source=src,evidence_state=state,runtime_evidence=evidence))
decision('P05-D01',[1,2,38],'入口、模型与写入路线','action, prompt, provider, mock, template, theme','create/revise; mock/LLM; template/python-pptx or no-template/PptxGenJS','request 校验后规划；template 真值决定写入后端；CLI theme 覆盖 deck.theme','deck JSON + PPTX + response','不是 capability-aware 路由；template 带旧页实测 KeyError(None)',refs('python_backend/skill_api.py','handle_skill_request'),'runtime_mock_js_and_template_failure','validation/maps-probes.json; validation/baseline-run.json')
decision('P05-D02',[3,4,5,21],'来源装载与展示','source text/path/url, trustLevel, priority, sourceDisplayMode','hidden/notes/footnote/appendix; text/local/url loaders','来源按输入顺序加载提供 context；trust/priority仅metadata，不是事实冲突求解；来源引用分配不证明句级事实','loaded_sources, excerpts, source refs, assumptions','5000字符裁剪提示；没有可验证的 claim/evidence 冲突决策',refs('python_backend/source_loader.py','load_source_contexts')+refs(smart,'normalize_deck_source_metadata','create_slide_source_ref')+refs(js,'renderSlide'),'runtime_normal_metadata','validation/baseline-run.json')
decision('P05-D03',[6,7,8,19,29],'Mock 元数据推断','prompt string','keyword priority lists; six built-in themes; fallback','受众/用途/语气关键词；title>36→33+...；语言固定en-US','audience/scenario/tone/theme/title/language','不是多语言识别；标题截断无容量测量',refs(smart,'infer_audience','infer_scenario','infer_tone','infer_theme','infer_language','infer_deck_title'),'runtime_boundary','validation/maps-probes.json')
decision('P05-D04',[9,11,12,13,14,15,16,17,22,25,26,27],'Mock 页序与页数','prompt + source context','预定义九页：title/agenda/bullet/two-column/comparison/timeline/chart/summary/closing','5..12 clamp 后切片预定义页；强制末页closing；不是章节预算或故事线搜索','slides/objective/bullets/chart synthetic data','1→5、12→9；固定示例数据不代表输入事实',refs(smart,'build_mock_deck','clamp_slide_count','infer_slide_count','normalize_closing_slide'),'runtime_mock','validation/maps-probes.json; validation/verify-res-p05-01-02.json')
decision('P05-D05',[2,5,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,37],'模型规划与 schema 修复','prompt + source excerpts + numerical hints + upstream SKILL/schema','模型输出 JSON；schema-valid/repair/final failure','system/create/revise prompts；数值密度≥3才提示chart；模型选择布局等不可解释黑盒；初次+最多2次repair','schema-validated deck','syntax/schema errors repair；不等同所有 DEC 都有算法/可解释候选评分',refs(smart,'build_system_prompt','build_create_prompt','build_revise_prompt','extract_numerical_hints','execute_planning_flow','build_repair_prompt'),'source_only_model_black_box')
decision('P05-D06',[20,26,39],'图表数据修复/降级','chart categories/series/type','bar/line/pie/area；numeric coercion；truncate longer series；bullet fallback','不向短series补零；不可修复则改bullet并添加assumptions','repaired chart or bullet + fallback notes','仅覆盖 planner；Python直接renderer另有短series补零',refs(smart,'repair_chart_data','validate_chart_slides')+refs(py,'_render_chart'),'runtime_direct_renderer_boundary','validation/maps-probes.json')
decision('P05-D07',[20,29,39],'Mock 修订意图与编辑','existing deck JSON + revision prompt','shorten/expand/restructure/reframe/clarify/emphasize/conclusion; slideN + six layout keywords','regex dispatch；compress merge少量bullet；expand canned内容；page-specific覆盖；clarify只取6项各80字符','完整新deck JSON再写PPTX','clarify未加裁剪说明；没有对象身份保留、PPTX读入或局部写入',refs(smart,'apply_heuristic_revision','detect_revise_intent','apply_page_specific_revision','compress_deck','expand_deck','clarify_deck','make_more_conclusion_driven','reframe_audience'),'runtime_revision_and_boundary','validation/maps-probes.json; validation/revision.txt')
decision('P05-D08',[28,30,32],'模板解析与布局映射','PPTX template path + requested layout','name hints→placeholder structure→content fallback→layout0','13个schema布局映射＋blank；不是候选评分；只提取first master相关布局；theme查master后代遗漏独立关系','TemplateConfig: layouts/slots/EMU/mapping/fonts/colors','kpi/swot/image-text/funnel未映射→layout0+bullet；不存在通用semantic slot solver',refs(template,'parse_template','_extract_layouts','_build_layout_mapping','_find_content_layout','_extract_theme_colors','_extract_fonts')+refs(py,'_get_layout','_render_slide'),'runtime_template_parse_and_boundary','outputs/maps-probes/template-parsed.json; validation/maps-probes.json')
decision('P05-D09',[29,34,35],'主题/字体优先级','template or theme name or deck._theme','template→name→business-clean; injected _theme→file→JS default','token merge；CJK font stack声明，不证明安装或字体覆盖；revision tech→不存在的tech-modern','colors/fonts/chartColors/theme','Python warn后fallback；JS missing/bad theme默认；不全面检查对比度',refs(template,'resolve_theme','load_theme','template_config_to_theme','_font_stack')+refs(smart,'apply_requested_theme')+refs(js,'resolveTheme','mergeTheme','pickTextColor'),'runtime_theme_failure_and_low_contrast','validation/maps-probes.json; validation/verify-res-p05-01-02.json')
decision('P05-D10',[17,18,32,33,34,35],'JS 布局固定分派与几何','17 layout keys + content fields','15 render functions；agenda/section/summary共用','固定英寸坐标或简单算式；文本shrinkText；timeline5项/process4项，无显式损失记录','native text/shapes/table；chart取决于native flag','不测量容量、不搜索/评分、不保证不溢出；image-text是示意框',refs(js,'renderSlide','addTextBox','renderTimelineSlide','renderProcessSlide','renderKpiSlide','renderSwotSlide','renderFunnelSlide','renderImageTextSlide'),'normal_runtime_other_layouts_source_only','validation/baseline-run.json')
decision('P05-D11',[23,24,36],'视觉项分类与图片位置','visual string/dict/path/url/position preset','image/placeholder/description；Python local/url；JS file existence','分类后选择预设位置；Python limited MIME/size/URL加载规则；没有素材搜索/必要性算法','image/text/placeholder','JS无法下载url或缺文件时改视觉建议文本；不能将图示描述自动视为可编辑SmartArt；没有通用crop候选搜索',refs('python_backend/image_handler.py','classify_visual','resolve_image','get_position')+refs(js,'classifyVisual','getVisualPosition','renderVisualsOnSlide'),'source_only')
decision('P05-D12',[26,38],'图表输出策略','chart data + _nativeCharts + canvas availability','PNG ChartJS default / native PptxGenJS; Python native','--native-charts显式标志或canvas缺失使用native；与全对象能力无关','raster chart or native chart+workbook','无canvas换native并无统一fallback trace；Python直接renderer会补零',refs(js,'renderChartSlide','renderChartImage','toChartType','buildFromFile')+refs(py,'_render_chart'),'runtime_normal_raster_and_native','validation/maps-probes.json; validation/baseline-run.json')
decision('P05-D13',[37],'备注与页脚','needsSpeakerNotes/sourceDisplayMode/page/layout','text notes; numeric footer; no motion choices','notes与source文本组合；title/closing跳过数字页脚','notes parts +普通文本页码','没有动画/切换或完整页脚对象语义',refs(js,'renderSlide','addFooter')+refs(py,'_add_notes','_add_footer'),'runtime_notes','validation/maps-probes.json')
decision('P05-D14',[39,40],'独立 QA 与评分','PPTX file / deck JSON / strict flag','edge_margin/overlap_candidate/empty_slide/text_only；JSON heuristic checks','LibreOffice→PDF→JPEG；PPTX bbox两两overlap；严格CLI有issue→非零；非自动闭环','report/images/heuristic score/CLI exit','27 issues；暗底低对比未检；没有fact/editability/pixel QA或自动修复轨迹',refs('python_backend/visual_qa.py','run_visual_qa','analyze_visual_quality','_export_images')+refs('python_backend/quality_scorer.py','score_deck','check_revision_quality'),'runtime_strict_failure','validation/verify-res-p05-01-02.json')
coverage=[]
for row in baseline['决策链']:
 id,name=row[:2];hits=[n['id'] for n in nodes if id in n['dec_ids']]
 coverage.append({'dec_id':id,'baseline_name':name,'node_ids':hits,'status':'Partial' if hits else 'Not found','boundary':'映射只说明相关候选逻辑；不表示统一决策节点实现或验收' if hits else '未发现内容关系图/可解释候选评分算法；prompt指令不算实现'})
decision_map={'artifact_type':'ProjectDecisionMap','requirement_id':'RES-P05-03','source_commit':commit,'nodes':nodes,'unified_dec_crosswalk':coverage,'project_specific':['mock canned page roster','dual template/JS rendering','source excerpt cutoff','chart repair vs direct renderer zero padding','footer skip title/closing'],'consumer':'RES-031跨项目比较与后续架构选择；不在产品中直接执行','scope':'所有影响结构/视觉的主要调用路径分组覆盖；模型/Tavily/库内算法不臆测；源代码证据与运行证据分列'}

# Geometry is expression data, not evaluated coordinates or invented named slots.
layout_functions={'title':'renderTitleSlide','agenda':'renderAgendaSlide','section':'renderAgendaSlide','bullet':'renderBulletSlide','two-column':'renderTwoColumnSlide','comparison':'renderComparisonSlide','timeline':'renderTimelineSlide','process':'renderProcessSlide','table':'renderTableSlide','chart':'renderChartSlide','quote':'renderQuoteSlide','summary':'renderAgendaSlide','closing':'renderClosingSlide','kpi':'renderKpiSlide','swot':'renderSwotSlide','image-text':'renderImageTextSlide','funnel':'renderFunnelSlide'}
fields={'title':['title','subtitle'],'agenda':['bullets'],'section':['bullets'],'summary':['bullets'],'closing':['title','subtitle','bullets'],'bullet':['bullets','visuals'],'two-column':['left','right'],'comparison':['left','right'],'timeline':['bullets'],'process':['bullets'],'table':['table.columns','table.rows'],'chart':['chart','bullets'],'quote':['quote','bullets'],'kpi':['kpis'],'swot':['quadrants'],'image-text':['imagePosition','subtitle','bullets'],'funnel':['funnel']}
lines=(root/js).read_text(encoding='utf-8').splitlines();layouts=[]
for name,func in layout_functions.items():
 r=ref(js,func);fragment=lines[r['line_start']-1:r['line_end']];geo=[]
 styles=[]
 for i,l in enumerate(fragment,r['line_start']):
  pairs=re.findall(r'\b(x|y|w|h)\s*:\s*([^,}]+)',l)
  if pairs:geo.append({'line':i,'expressions':dict(pairs),'context':l.strip()})
  style_pairs=re.findall(r'\b(fontSize|fontFace|color|fill|line|bold|italic|align|valign)\s*:\s*([^,}]+)',l)
  if style_pairs:styles.append({'line':i,'expressions':dict(style_pairs),'context':l.strip()})
 caps=[{'line':i,'rule':l.strip()} for i,l in enumerate(fragment,r['line_start']) if '.slice(' in l or 'Math.min(' in l or 'Math.ceil(' in l or 'const cols' in l or 'const rows' in l]
 layouts.append({'layout':name,'applies_when':'deck.slides[].layout == '+name,'content_bindings':fields[name],'slot_model':'程序字段/绘图位置，无正式命名slot schema','geometry_units':'inches','geometry_expressions':geo,'geometry_limit':'x/y/w/h properties按源码逐行提取；shorthand变量需结合源码函数，未求值；common header/footer另列','capacity_rules':caps,'capacity_limit':'没有可验证字符容量/fit solver；文本默认shrinkText；过多内容可能溢出或slice裁剪','tokens':'_t.colors/_t.fonts/_t.chartColors','style_expressions':styles,'inheritance':'global resolved theme + renderer overrides; no layout inheritance tree','source':[r]})
themes=[]
for p in sorted((root/'assets/themes').glob('*.json')):
 if p.name=='theme-schema.json':continue
 themes.append({'asset':p.name,'tokens':json.loads(p.read_text(encoding='utf-8')),'source':ref(str(p.relative_to(root)).replace('\\','/'))})
schema=json.loads((root/'deck-schema.json').read_text(encoding='utf-8'))
parsed=json.loads((out/'outputs/maps-probes/template-parsed.json').read_text(encoding='utf-8'))
template_map={'artifact_type':'ProjectTemplateMap','requirement_id':'RES-P05-04','source_commit':commit,'js_layouts':layouts,'common_geometry_sources':refs(js,'addTextBox','addSlideHeader','addFooter','addBulletList','getVisualPosition'),'built_in_themes':themes,'ir':{'format':'Deck JSON schemaVersion0.3.0','schema':schema,'source':ref('deck-schema.json'),'limits':'additionalProperties false验证前；_theme在验证后注入。没有统一object identity、edit patches、候选评分、bbox IR。'},'template_path':{'source':refs(template,'parse_template','_extract_layouts','_build_layout_mapping','_extract_theme_colors','_extract_fonts')+refs(py,'render_deck_with_template','_render_slide'),'observed_fixture':parsed,'slot_units':'EMU; 914400EMU/inch','mapping':'name substring→placeholder structure→content fallback; blank plus13keys；Pythonrender map13keys/11functions','unmapped':['kpi','swot','image-text','funnel'],'fallback':'layout0 + _render_bullet；不是全17布局支持','inheritance':'打开template保留其master/layout parts；实际renderer大量固定坐标而非填满placeholder；主题颜色/字体只搜索master内a:theme，独立关系遗漏','capacity':'模板slot有EMU几何，无文字/内容容量模型','failures':'带旧页template删除r:id namespace错误；empty template可写但KPI丢失，directchart缺值补零','runtime_evidence':'validation/maps-probes.json'},'consumer':'RES-031模板/IR比较，后续slot与容量设计依据','scope':'17JS key/15函数、6theme、完整IR约束、实测11layout/58placeholder data；不表示产品模板引擎已实现'}

caps=[]
descriptions={
1:('Partial','创建/保存新PPTX；不读入普通PPTX为可保真编辑IR。',refs(js,'buildDeck')+refs(py,'render_deck_with_template')),
2:('Partial','生成新页；JSON修订重排/增删后整体重建，无持久slide/object identity。',refs(smart,'apply_heuristic_revision')+refs(js,'renderSlide')),
4:('Partial','template路径加载原master，但已有页模板失败；无master对象CRUD。',refs(template,'parse_template')+refs(py,'render_deck_with_template')),
5:('Partial','解析11布局与placeholder；映射13schema key；JS17固定key。',refs(template,'_build_layout_mapping')+refs(js,'renderSlide')),
6:('Fallback','六JSON主题可用；template独立theme关系漏读→默认颜色/字体；revision tech-modern→business-clean。',refs(template,'_extract_theme_colors','_extract_fonts','load_theme')),
7:('Partial','读取placeholder idx/name/type/EMU；renderer大量固定textbox，缺统一slot匹配/容量。',refs(template,'_extract_layouts')+refs(py,'_fill_placeholder')),
8:('Partial','原生textboxes固定位置/font，不能任意对象CRUD/文字容量验证。',refs(js,'addTextBox')+refs(py,'_add_textbox')),
9:('Partial','字体/字号/bold/italic/bullets等有限格式；无完整rich-run/段落编辑协议。',refs(js,'addTextBox','addBulletList')+refs(py,'_add_textbox','_add_bullet_list')),
10:('Partial','JS写lang字段；mock infer_language固定en-US，无文字方向/脚本识别。',refs(js,'buildDeck')+refs(smart,'infer_language')),
11:('Partial','有限roundRect/rect等原生shape；无通用AutoShape对象模型与操作。',refs(js,'renderKpiSlide','renderFunnelSlide')+refs(py,'_add_rect')),
12:('Partial','timeline/process有限lines/arrows；无端点绑定/freeform通用编辑。',refs(js,'renderTimelineSlide','renderProcessSlide')),
13:('Partial','绘图调用顺序形成z-order；未提供group或通用reorder。',refs(js,'renderSlide','renderKpiSlide')),
14:('Partial','JS本地file addImage，Pythonlocal/url；尺寸/格式/下载边界；无完整crop或图片CRUD。',refs(js,'renderVisualsOnSlide')+refs('python_backend/image_handler.py','resolve_image')),
15:('Partial','SVG扩展名可分类为图片并交给图片库；未实测SVG保真/可编辑路径，icon描述不等于图标对象。',refs(js,'classifyVisual','renderVisualsOnSlide')+refs('python_backend/image_handler.py','classify_visual','resolve_image')),
16:('Partial','JS与empty-template Python均实际写原生表格；无merge/style全矩阵或已有表格编辑。',refs(js,'renderTableSlide')+refs(py,'_render_table')),
17:('Fallback','JS默认PNG；--native-charts实际写chart+embedded workbook；Pythonemptytemplate native，但directrenderer短series补零。',refs(js,'renderChartSlide','buildFromFile')+refs(py,'_render_chart')),
20:('Partial','GIF扩展名可作为图片输入，未验证动画保留；无audio/video专用IR或写入入口。',refs(js,'classifyVisual','renderVisualsOnSlide')+refs('python_backend/image_handler.py','classify_visual')),
23:('Partial','生成text speakerNotes实测；不支持复杂notes/旧notes保真更新。',refs(js,'renderSlide')+refs(py,'_add_notes')),
25:('Partial','普通文本页码，title/closing略过；无原生日期/完整header-footer设置。',refs(js,'addFooter')+refs(py,'_add_footer')),
28:('Partial','fill/line/roundRect基础样式；没有完整阴影/反射/3D/效果CRUD。',refs(js,'renderKpiSlide','renderSwotSlide')+refs(py,'_add_rect')),
30:('Partial','deck/page/name基础metadata；无跨生成修订稳定identity/OOXML对象追踪。',refs(js,'buildDeck')+refs(smart,'renumber_slides')),
}
for row in baseline['PowerPoint对象矩阵']:
 id,name=row[:2];n=int(id.split('-')[1]);status,detail,src=descriptions.get(n,('Unsupported','项目IR和render/修订接口未暴露此类对象的可用执行路径；依赖库潜在能力不能代替项目能力。',[ref('deck-schema.json'),ref(js,'renderSlide'),ref(py,'_render_slide')]))
 runtime='native_chart/table/notes结构证据见maps-probes；普通文本/shape见baseline' if n in [1,2,8,9,11,16,17,23,25,30] else '模板/主题见maps-probes' if n in [4,5,6,7] else 'source_only/not exposed'
 caps.append({'ppt_id':id,'baseline_name':name,'status':status,'operation_scope':detail,'source':src,'evidence_state':runtime,'evidence':['validation/maps-probes.json','validation/verify-res-p05-01-02.json'],'full_baseline_operations_supported':False})
capability_map={'artifact_type':'ProjectCapabilityMap','requirement_id':'RES-P05-05','source_commit':commit,'objects':caps,'status_definition':{'Native':'限定操作原生实现且实测；本map不以一项原生写入代表完整对象能力','Partial':'只暴露对象/操作子集；逐条写范围','Fallback':'路线含降级/替代，原因明确','Unsupported':'P05 IR/API/renderer未暴露执行路径；不是库自身能力判定'},'render':{'status':'Partial','routes':'no-template JS新PPTX；template Python新PPTX；LibreOffice独立PDF/JPEG','evidence':'validation/maps-probes.json; validation/baseline-run.json','boundary':'已有页模板CLI失败；emptytemplate直接写入成功；未用PowerPoint打开确认；本轮新对象只结构核对'},'qa':[{'name':'schema/JSON heuristic','status':'Partial','source':refs(smart,'execute_planning_flow')+refs('python_backend/quality_scorer.py','score_deck'),'boundary':'结构/内容密度启发式，非事实准确性/全对象/像素可读性'}, {'name':'visual_qa','status':'Partial','source':refs('python_backend/visual_qa.py','run_visual_qa','analyze_visual_quality'),'evidence':'outputs/normal-qa/visual-qa-report.json','boundary':'strict exit1,27issues；bbox误报候选；lowcontrast未检，高风险空集合不表示通过'}, {'name':'fact QA','status':'Unsupported','boundary':'无claim/evidence事实验证器'}, {'name':'editability/PowerPoint QA','status':'Unsupported','boundary':'没有原生对象可编辑性测试或PowerPoint兼容性验收入口'}, {'name':'automatic QA repair loop','status':'Unsupported','boundary':'qa-visual独立命令，无问题到局部修订再验收闭环'}],'revision':[{'name':'deck JSON revision','status':'Partial','source':refs(smart,'apply_heuristic_revision','build_revise_prompt'),'evidence':'outputs/revision/py-revised-deck.pptx','boundary':'mock8→6重新生成；LLMrevise source-only；canned覆盖/clarify裁剪未保护事实与identity'}, {'name':'existing PPTX preserving edit','status':'Unsupported','source':refs(py,'render_deck_with_template'),'evidence':'validation/template-direct.txt','boundary':'接受template不等于edit；删除旧slides意图且namespace错误；无保真读取IR/对象patch'}, {'name':'direct chart data integrity','status':'Fallback','source':refs(py,'_render_chart'),'evidence':'validation/maps-probes.json','boundary':'directrender输入[7]、3categories→[7,0,0]；planner先validate正常路线不可混为同一结论'}],'license':'根AGPL3/package AGPL-3.0-only vs pyproject/originallock Apache2未解决，禁止据此决定复制/分发','consumer':'RES-031能力对照；RES-032许可证/复用决策；架构选择；不算产品AC','scope':'PPT001–030全部列出，按P05公开流程与原需求操作范围判断；未做完整对象编辑/PowerPoint验收'}
for name,value in [('ProjectDecisionMap.json',decision_map),('ProjectTemplateMap.json',template_map),('ProjectCapabilityMap.json',capability_map)]:
 value['source_files_sha256']=sources
 (out/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Built {len(nodes)} decision groups / {len(coverage)} DEC mappings, {len(layouts)} layout keys / {len(themes)} themes, {len(caps)} object boundaries')
